name: video-depthify
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.12
  - pytorch=2.8.0
  - torchvision=0.22.0
  - pip
  - pip:
     - opencv-python==4.11.0.86
     - timm==1.0.10
     - numpy==2.2.3
