name: video-depthify
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.12
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/nightly/cpu
    - torch
    - torchvision
    - opencv-python==4.11.0.86
    - timm==1.0.10
    - numpy==2.2.3
