name: video-depthify
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10.12
  - pytorch=2.4.0
  - pytorch-cuda=11.7
  - torchvision=0.19.0
  - pip
  - pip:
     - opencv-python==4.11.0.86
     - timm==1.0.10
     - numpy==2.2.3